### ISSUE TITLE
No status message when saving configuration changes.

### ISSUE THREAD

**Issue by PaulHoza** [backdrop-contrib/googleanalytics#11]
When I added this module and saved the changes to the admin form, it didn't trigger a status message, but saving did occur.  This is likely similar to Issue #1060 of core (https://github.com/backdrop/backdrop-issues/issues/1060) where this just needs an added backdrop_set_message.

I am posting this issue for now, as I don't have time to implement/test this to see if I can figure it out.

**Comment by ghost** [comment]
Yes, same issue here. No confirmation message upon saving /admin/config/system/googleanalytics

**Comment by jenlampton** [comment]
Thanks for the reports, a fix for this issue will be in the next release.
