### ISSUE TITLE
For better google pagespeed results, add a link tag with rel="preconnect"

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/googleanalytics#15]
I was running Lighthouse to figure out how to make my pages load faster, and one of the recommendations is to `Preconnect to required origins'. Since the GA module is responsible for adding the origin of `https://www.google-analytics.com` we should probably add the link tag in this module too.

**Comment by jenlampton** [comment]
I've posted a PR that adds the link tag, but I want to test it in production for a while before I merge it in.

**Comment by sillygwailo** [comment]
I did a before (without the PR) and after (with the PR), contained in the zip file, which has Lighthouse reports of my humble personal site.

[richard.eriksson.ca-lighthouse.zip](https://github.com/backdrop-contrib/googleanalytics/files/5031868/richard.eriksson.ca-lighthouse.zip)

**Comment by jenlampton** [comment]
I just pushed 2 updates to the PR, it seems to be helping now :)
