### ISSUE TITLE
Trying to access array offset on value of type null in googleanalytics_preprocess_search_results() (line 488

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/googleanalytics#26]
> Notice: Trying to access array offset on value of type null in googleanalytics_preprocess_search_results() (line 488 of /var/www/fmr/dev/src/modules/contrib/googleanalytics/googleanalytics.module).

We are getting the above error. My colleage thinks he knows what the problem is and hopefully we'll be able to submit a PR in a few minutes.

This happens when we do a search with zero results.

![image](https://user-images.githubusercontent.com/3144571/176116732-df725f8c-5e08-4719-8bae-82aeff7f3b6a.png)

**Comment by stpaultim** [comment]
It seems like this issue has been fixed in DEV branch, but fix has not yet been released.

**Comment by jenlampton** [comment]
A new release is coming out right now :)
