### ISSUE TITLE
Notice: Undefined variable: create_only_fields in googleanalytics_preprocess_layout()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/googleanalytics#27]
Seeing this error in watchdog:

```
Notice: Undefined variable: create_only_fields in googleanalytics_preprocess_layout() 
(line 284 of .../modules/contrib/googleanalytics/googleanalytics.module).
```

The problem seems to be that line 284 is this:

```
    $create_only_fields = array_merge($create_only_fields, $codesnippet_create);
```

This is the first usage of `$create_only_fields ` in the function, so of course it is an undefined variable. Changing that line to

```
    $create_only_fields = $codesnippet_create;
```

fixes the problem.

**Comment by laryn** [comment]
Works for me.

**Comment by stpaultim** [comment]
Came to report the same problem. We are ALSO getting this error in addition to the error reported above:

```
Warning: array_merge(): Expected parameter 1 to be an array, null given in googleanalytics_preprocess_layout() 
(line 284 of /src/modules/contrib/googleanalytics/googleanalytics.module).
```
Same line number so hopefully the same solution fixes both. We will test PR and report back here.

**Comment by rajpaul** [comment]
@stpaultim The PR by @bugfolder fixed both of the notice/warning.

**Comment by stpaultim** [comment]
@rajpaul - Thanks for the confirming this. Hope to see this in a new release.
