### ISSUE TITLE
The function googleanalytics_preprocess_layout() (googleanalytics.module:375) called deprecated function variable_get()

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/googleanalytics#29]
I'm getting this notice on a site using the latest version of Backdrop CMS and Google Analytics.

`The function googleanalytics_preprocess_layout() (googleanalytics.module:375) called deprecated function variable_get(). It will be removed in the next major release of Backdrop. `

![image](https://user-images.githubusercontent.com/3144571/193727796-64b6b588-7922-40d8-bedc-fddd13329816.png)

**Comment by avpaderno** [comment]
In the googleanalytics.module file, the following lines call `variable_get()`.

```php
    if (variable_get('googleanalytics_tracker_anonymizeip', 1)) {
      $create_only_fields['anonymize_ip'] = TRUE;
    }
```

```php
    elseif (variable_get('googleanalytics_cache', 0) && $url = _googleanalytics_cache('https://www.googletagmanager.com/gtag/js')) {
      // Should a local cached copy of gtag.js be used?
      $query_string = '?' . variable_get('css_js_query_string', '0');
      $library = $url . $query_string;
    }
```

They are all lines in `googleanalytics_preprocess_layout()`, which initializes `$config` with `$config = config('googleanalytics.settings');`.

* `variable_get('googleanalytics_cache', 0)` needs to be replaced by `$config->get('cache')`, and 
* `variable_get('googleanalytics_tracker_anonymizeip', 1)` is probably replaced by `$config->get('tracker_anonymizeip')`,
* `variable_get('css_js_query_string', '0')` must be replaced with a call to `state_get('css_js_query_string', '0')`.

**Comment by avpaderno** [comment]
I created a PR to fix this.

**Comment by klonos** [comment]
Assigning this to @jenlampton, since she's the maintainer of the project :)

**Comment by jenlampton** [comment]
I don't see any other instances of `css_js_query_string` in the module, so I don't understand why that went to state and not config....

Aha! that is not a GA thing but a Backdrop core thing, duh:

```
function _backdrop_flush_css_js() {
  // The timestamp is converted to base 36 in order to make it more compact.
  state_set('css_js_query_string', base_convert(REQUEST_TIME, 10, 36));
}
```

If this is the case, then I think we should give it the same default value of `base_convert(REQUEST_TIME, 10, 36)`.

**Comment by jenlampton** [comment]
I've left two small comments on the PR https://github.com/backdrop-contrib/googleanalytics/pull/30 if those can be updated, this is ready to merge :)

**Comment by jenlampton** [comment]
I decided to merge the PR as-is and make the two changes afterward. I will make a new release today that brings this project up to date with Drupal [7.x-2.8](https://www.drupal.org/project/google_analytics/releases/7.x-2.8)

**Comment by avpaderno** [comment]
I took the default value for *css_js_query_string* from Backdrop core, which uses the following code in [`backdrop_pre_render_styles()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_pre_render_styles/1).

```php
// A dummy query-string is added to filenames, to gain control over
// browser-caching. The string changes on every update or full cache
// flush, forcing browsers to load a new copy of the files, as the
// URL changed.
$query_string = !defined('MAINTENANCE_MODE') ? state_get('css_js_query_string', '0') : '';
```
