### ISSUE TITLE
New Release 2.8

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/googleanalytics#33]
I see there is a tag for 2.8, but no release yet. Is this intentional?

I have a site with a log full of these warnings: https://github.com/backdrop-contrib/googleanalytics/issues/29

Would be nice to update this. Thanks.

@jenlampton

**Comment by stpaultim** [comment]
I just found an old discussion about this in Zulip. Seems that there was an error with the release. @jenlampton planned to fix it, but must have slipped her mind. 

No urgent rush.

**Comment by herbdool** [comment]
@stpaultim is this still a problem? I see a 2.8 release with files. Does it contain the right commits?

**Comment by stpaultim** [comment]
@herbdool It seems the 2.8 release happened on the same day I posted this note. It seems someone simply forgot to close this issue. Possibly me.
