### ISSUE TITLE
should analytics.js be replaced with gtag.js?

### ISSUE THREAD

**Issue by paulrooney** [backdrop-contrib/googleanalytics#34]
Reference to analytics.js is here:
https://github.com/backdrop-contrib/googleanalytics/blob/1e396cf502cb552c189ff1d20c38049e93c5dcf5/googleanalytics.module#L16-L20

Drupal module uses gtag.js:
https://git.drupalcode.org/project/google_analytics/-/blob/4.x/google_analytics.module?ref_type=heads#L26

Recommendation at https://www.drupal.org/project/google_analytics is to use https://www.drupal.org/project/google_tag instead.

Should this module be adapted to use gtag.js, or should Backdrop users of the Google Analytics module switch to use the Google Tag module at https://github.com/backdrop-contrib/google_tag instead?

**Comment by herbdool** [comment]
In this issue, support for GA4 was added: https://github.com/backdrop-contrib/googleanalytics/issues/23. And when I look at the source of a Backdrop site it is loading `gtag` (aka googletagmanager) so it appears to be working. I don't know enough to understand why it still references `analytics.js` in `googleanalytics_api()`. Perhaps it's not doing anything or it's backwards compatible.
