### ISSUE TITLE
Undefined index: #user_category

### ISSUE THREAD

**Issue by sirkitree** [backdrop-contrib/googleanalytics#6]
When viewing a user edit screen like `/user/2/edit` I'm seeing the following notice:

Notice: Undefined index: #user_category in googleanalytics_form_user_profile_form_alter() (line 373 of /var/www/beta.vrsites.com/docroot/modules/contrib/googleanalytics/googleanalytics.module).

**Comment by sirkitree** [comment]
At `/admin/config/system/googleanalytics` under the "Users" tab, the option is set to "No customization allowed"
![google analytics beta vrsites com 2015-04-02 20-40-19](https://cloud.githubusercontent.com/assets/28543/6977339/7d2e838e-d978-11e4-9bf1-58a5ef7b4ad5.png)

**Comment by sirkitree** [comment]
Commenting out the line works for now, but I'm sure that's not the proper solution here.

**Comment by jromine** [comment]
#user_category was a Drupal 7 user profile thing.  It allowed for multiple
tabs on the user edit page. I don't think Backdrop has this. It's come up
before. Perhaps there should be a change record added.

**Comment by jenlampton** [comment]
We've got this change record: https://api.backdropcms.org/node/43511
