### ISSUE TITLE
GA JavaScript file not loaded.

### ISSUE THREAD

**Issue by xmacinfo** [backdrop-contrib/googleanalytics#7]
[Working too late is not recommended. Of course the module is working]

This module does not work. The GA script and settings are not loaded.

Tried without success:
- update from Drupal 7 to Backdrop where settings were converted to configs.
- uninstalling and installing the module.

In addition, tests are not passing:
- 62 failed
- 9 exceptions

**Comment by klonos** [comment]
I don't think this module is fully ported yet. No [official releases](https://github.com/backdrop-contrib/googleanalytics/releases), so might wanna keep an eye for when there is one.

**Comment by xmacinfo** [comment]
Started fixing the tests in a fork. Now the GA script and settings are loaded correctly in some of the test (verified in the verbose output).

Looks like the module does not correctly honor roles.

To be continued…

**Comment by xmacinfo** [comment]
Looks like Nathan fixed it here:
backdrop-contrib/googleanalytics@79b0a9c5e2debcabb5b623a1afb7c386ddc4baa9

I may have checkout the wrong files to start with.

**Comment by xmacinfo** [comment]
Well well well. Working too late in the middle of the night is not recommended!

Of course the module is working! I just need to remove the “do not track” flag in my browsers!
